### ISSUE TITLE
Change default namespace to `App\Transporter`

### ISSUE THREAD

**Issue by Gummibeer** [JustSteveKing/laravel-transporter#1]
Right now the default namespace is `App\Http\API\Requests` which at first looks cool but the classes inside are totally unrelated to my apps HTTP responsibilities.
These are classes describing a third-party API request, which will use HTTP as transport layer but in my app the responsibility is Guzzle/curl. These classes are in no way related to my app controllers, requests, resources, middleware or the apps HTTP kernel. Mixing them will only lead to trouble, misconceptions and a lot of brain hacking if you talk about app HTTP requests.

An alternative would be `App\Transporter` - it won't conflict with other packages (package name as namespace) and makes it clear that the classes inside are something totally custom.

**Comment by JustSteveKing** [comment]
That is a pretty good idea, I initially moved this under `App\Http\API\Requests` as it makes it feel like a logical grouping, however it might be worth reassessing this as you said it has nothing to do with your App Http layer as such. Perhaps a more accurate one would be `App\Transporter\Requests` as it allows then to also override certain aspects of transporter under the one namespace?

**Comment by Gummibeer** [comment]
Sure, also a good adjustment. But the top-level namespace should be a custom package specific one.

**Comment by JustSteveKing** [comment]
I agree!

**Comment by JustSteveKing** [comment]
It is done! See Release 0.3.0
