### ISSUE TITLE
Internal Server Errors with API

### ISSUE THREAD

**Issue by heychazza** [JustSteveKing/laravel-transporter#15]
Hey Steve,

When utilising transporter within an API, I receive a server error, but when called manually it works without any issues.

**CraftheadRequest**
```php
abstract class CraftheadRequest extends Request
{
    protected string $method = 'GET';
    protected string $baseUrl = 'https://crafthead.net/';
}
```

Then, my main request that extends..
```php
class NameToUUIDRequest extends CraftheadRequest
{
    public function username(string $username)
    {
        $this->setPath("profile/{$username}");

        return $this;
    }
}
```

And use it, like so..
```php
        $response = NameToUUIDRequest::build()->username($username)->send();

        if ($response->failed()) {
            return null;
        }

        return $response->json('id');
```

Any reason for this? I considered it may be the user agent, but tried it and same thing, and even manually tried API without agent and worked.

**Comment by JustSteveKing** [comment]
I will have to check out the API itself to see what the issue could be 🙂

It looks like you're using the package correctly though!

**Comment by heychazza** [comment]
> I will have to check out the API itself to see what the issue could be 🙂
> 
> It looks like you're using the package correctly though!

I've been trying to test, but I'm super confused, haha.

**Comment by heychazza** [comment]
Apologies for wasting your time, it seemed the API randomly (after a long time of being stable) started to error out randomly, which was confusing as I was using transporter with it ok for a while, haha.

https://github.com/astei/crafthead/issues/29#event-5359028893
