### ISSUE TITLE
Move destination overrides in a `to()` method

### ISSUE THREAD

**Issue by Gummibeer** [JustSteveKing/laravel-transporter#2]
In the current API I have to override the path with the same method I also adjust the payload. This feels wrong as changing the path is first something super rare as it's against the principle of that package. And You don't do the request with a path but to a path.
So an API like `to(path: '/foo/bar')` feels better. This could also allow adjusting the fragment and other URI segments.

**Comment by JustSteveKing** [comment]
I definitely think there is a lot that could be done in the `__callStatic` approach I currently set up - would happily accept a PR on this, or some guidance on what a friendlier DX would be

**Comment by Gummibeer** [comment]
The `__callStatic()` wouldn't need any adjustment. Just a new `to(...)` method on the class implementing the `with()` one.
The magic method will automatically do everything.

```php
CreateUserrequest::to(path: 'foo/bar')->with(payload: ['foo' => 'bar'])->send();
```

**Comment by JustSteveKing** [comment]
Refactoring how we forward calls to drop the requirement of named arguments will be a benefit for PHP 7.4 support - however it will all depend on the approach taken

**Comment by Gummibeer** [comment]
The problem is that the `to()` and `with()` method have to be callable as static method or on an instance. Otherwise you will have to construct the request manually.

**Comment by JustSteveKing** [comment]
perhaps I can do something in the call static method? If you have any ideas I'd love to hear/see them - I haven't used call static much, and also want to start moving things towards constants over floating string comparisons

**Comment by Gummibeer** [comment]
So the current problem with `__callStatic` and PHP7.4 is that you depend on `Request::with(headers: [])` to get `['headers' => []]` as `$arguments` in the `__callStatic()`?

The solution is simple: in case the user doesn't use named arguments they have to use positional arguments.
```php
Request::with([], ['X-Foo' => 'bar'])->send();
```

This works with PHP7 and also with `__callStatic`.
You could help by add PHP doc-blocks to the trait defining `__callStatic()`.

```php
/**
 * @method static Transporter to(string $path)
 * @method static Transporter with(array $payload, array $headers)
 */
```

That way the IDE can provide proper autocompletion and the user also knows the order and names of arguments.

**Comment by K2ouMais** [comment]
Yes... A doc-block over the methods would do the job, for people using PHP 7.4.

If you are going this route you can also change the union type from for example ```string|null``` to ```?string``` and ```array|null``` to ```?array```.

Thank you for this aproach.

**Comment by Gummibeer** [comment]
PS: I would still only document the PHP8 way - in case someone uses PHP7.4 they should be experienced enough to understand the IDE autocompletion and that they can't use PHP8 named arguments and have to switch to positional arguments instead.
This will still "force" people to PHP8 but allow people like @K2ouMais on legacy apps to use the package.

**Comment by JustSteveKing** [comment]
Any chance on submitting a PR @Gummibeer ? I want to make sure I understand exactly what you mean :)

**Comment by Gummibeer** [comment]
Yeah, wait a moment.

**Comment by JustSteveKing** [comment]
Thanks @Gummibeer

**Comment by JustSteveKing** [comment]
A huge rebuild is underway thanks to the help from @Gummibeer please check the main branch as a lot of changes are coming to simplify and lean on the power of Laravel. This will not work yet - but sending requests directly will

**Comment by JustSteveKing** [comment]
Closing for now as this has moved to a different approach - I will create an issue for PHP 7.4 support

**Comment by JustSteveKing** [comment]
@K2ouMais if you're interested: https://github.com/JustSteveKing/laravel-transporter/issues/5
