### ISSUE TITLE
View the payload?

### ISSUE THREAD

**Issue by xazinji** [JustSteveKing/laravel-transporter#23]
I'm currently debugging an issue and would like to see what exactly is being send to the third party API.

So is there any way to view the full raw output of what is being send?

**Comment by JustSteveKing** [comment]
Hey @xazinji sorry - for some reason I didn't get notified of this issue (I will look into that).

Currently there isn't a way to do that, but in your request you can simply:

```php
class YourRequest extends Request
{
    public function getData(): array
    {
        return $this->data ?? [];
    }
}
```

I will add this to the core library, unless you would like to drop a PR in for it?

**Comment by JustSteveKing** [comment]
@xazinji I will add this get data helper method to the package, as it's a good idea. Please let me know if this is what you were looking for?

Getting the raw data from the request will always be an array, as it isn't encoded in any way until it is sent - which is part of Laravel Core using the Pending Request

**Comment by xazinji** [comment]
Thank you, that is exactly what I was looking for. I ended up adding it myself, but having it in the package is a great addition.

**Comment by JustSteveKing** [comment]
Hey @xazinji - please see release 0.9.5 😄
