### ISSUE TITLE
Sending XML

### ISSUE THREAD

**Issue by jessarcher** [JustSteveKing/laravel-transporter#26]
Hey @JustSteveKing!

Love this package :)

This isn't really an issue, but I have an API where I need to send XML for some requests and was hoping to use this package, so I created this trait that I thought might be worth sharing:

```php
<?php

namespace App\Transporter;

use Illuminate\Http\Client\Response;

trait SendsXml
{
    public function withXml(string $xml): static
    {
        $this->request
            ->withHeaders(['Accept' => 'application/xml'])
            ->withBody($xml, 'application/xml');

        return $this;
    }

    public function send(): Response
    {
        return $this->request->send(
            $this->method,
            $this->getUrl()
        );
    }
}
```

I don't think it quite handles all of the use cases Transporter is designed for, but for my case it worked a treat.

The usage in the request then looks something like this:

```php
<?php

declare(strict_types=1);

namespace App\Transporter\Requests;

use App\Transporter\SendsXml;
use JustSteveKing\Transporter\Request;

class MyXmlRequest extends Request
{
    use SendsXml;

    protected string $method = 'POST';

    protected string $path = '/my-endpoint';
}
```

And then using the request looks something like this:

```php
MyXmlRequest::build()->withXml($xml)->send();
```

Feel free to do whatever you like with it and to close this issue whenever you like.

**Comment by jessarcher** [comment]
Another one you may be interested in:

```php
<?php

namespace App\Transporter;

trait Params
{
    public function withParam(string $name, string $value): static
    {
        return $this->setPath(str_replace("{{$name}}", $value, $this->path));
    }
}
```

Usage:

```php
<?php

declare(strict_types=1);

namespace App\Transporter\Requests;

use App\Transporter\Params;
use JustSteveKing\Transporter\Request;

class MyRequest extends Request
{
    use Params;

    protected string $method = 'GET';

    protected string $path = '/api/v1/posts/{post}';
}
```

```php
MyRequest::build()->withParam('post', '123')->send();
```

I took it a step further and added a specific method to the request:

```php
public function withId(string $id): static
{
    return $this->withParam('id', $id);
}
```

```php
MyRequest::build()->withId($id)->send();
```

I like this because it keeps knowledge of the path within the Response class.

The implementation is pretty brittle in that it doesn't handle an invalid param, but hopefully this helps someone and maybe inspires some ideas.

**Comment by JustSteveKing** [comment]
Hey @jessarcher - firstly thank you! Always happy to hear people enjoy using my packages!

So this is an amazing idea for using XML, making it opt in as it's less common makes a lot of sense! Will definitely add this, or accept a PR for it - either way, awesome!

The parameters I like, but I'm pretty sure I have a way to do this - but I like what you've done here! Will definitely have a look to see what I can do here!

Any other ideas, my ears are definitely open! I've been doing direct API integrations recently for tutorials - but transporter is definitely my preferred way (of course).

**Comment by JustSteveKing** [comment]
Thanks @jessarcher - this has been added to release 0.9.5 today 😄
