### ISSUE TITLE
withToken() method does not exist despite mentioned many times in Readme.md

### ISSUE THREAD

**Issue by ziming** [JustSteveKing/laravel-transporter#34]
Tried to call this method as the readme says, but it is not found (withToken())

MyRequest::build()->withToken($token)->send()

Im dealing with an API where i need a new token every transaction, so I need to call the authenticate api first, get the token then call the transaction API each time

**Comment by JustSteveKing** [comment]
This is quite strange @ziming as `build` will return a PendingRequest from Laravel

**Comment by ziming** [comment]
Ah turns out is PHPStorm mistake in saying method not found
