### ISSUE TITLE
Ability to pass an ID or other relevant params via the request URL

### ISSUE THREAD

**Issue by VimKanzoGH** [JustSteveKing/laravel-transporter#35]
I'm working on a project where I have to perform crud operations often, but unfortunately, I'm not able to update an item that requires you to pass the id via the request e.g /v1/post/{id}.

I would greatly appreciate it if this feature or all possible crud operations are available in the package. I love the package and it makes life easier for me in the current project I'm working on.

Thanks

**Comment by JustSteveKing** [comment]
See the new release @VimKanzoGH 😄
