### ISSUE TITLE
`GET` requests don't support query parameters

### ISSUE THREAD

**Issue by edalzell** [JustSteveKing/laravel-transporter#47]
In `getUrl()` there's this code:

```php
if (Str::of($this->method)->upper()->contains('GET', 'HEAD')) {
    return $this->path();
}
```

So any query params set (via `withQuery`) aren't appended.

I can PR a fix, was this intentional behaviour?

**Comment by edalzell** [comment]
> I would happily accept a PR here! I need to pick up some of the changes I wanted to add to this library

Ya I was going to PR it, then realized I'm on a L9 project and can't go to L10 yet, so I ended up overloading `getUrl` in my base request class.

**Comment by edalzell** [comment]
> I would happily accept a PR here! I need to pick up some of the changes I wanted to add to this library

@JustSteveKing sorry for the delay, forgot about this, I've PR'ed this.

**Comment by JustSteveKing** [comment]
Thanks @edalzell 😍
