### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by JustSteveKing** [JustSteveKing/laravel-transporter#5]
PHP 7.4 support has been requested, if enough people are interested I will consider adding and supporting this

**Comment by K2ouMais** [comment]
I am interested, but I dont think there will be enough people to make you change your mind.

I have no problem with it... Will just fork and make the changes to make it work for me.

Thank you

**Comment by JustSteveKing** [comment]
With the latest refactor, it shouldn't be too much work - but will investigate how viable it is without having a larger knock on effect.

I would of course accept a PR 🙂

**Comment by K2ouMais** [comment]
I probably will only be able to take a look at it on Monday, but now the package looks clean AF 🙂

**Comment by K2ouMais** [comment]
Hi, 

I took a look and it seems you have also a new dependency.

I would have to PR the dependency also to make this php7.4 compatible.

Sorry, but I won't do that. You can close this issue.

See ya

**Comment by K2ouMais** [comment]
Hi, 

I took a look and it seems you have also a new dependency.

I would have to PR the dependency also to make this php7.4 compatible.

Sorry, but I won't do that. You can close this issue.

See ya

**Comment by K2ouMais** [comment]
Hi, 

I took a look and it seems you have also a new dependency.

I would have to PR the dependency also to make this php7.4 compatible.

Sorry, but I won't do that. You can close this issue.

See ya

**Comment by JustSteveKing** [comment]
Which dependency was that?

**Comment by K2ouMais** [comment]
I mean your other package uri-builder.

It is also only php8.

**Comment by JustSteveKing** [comment]
Yea I was pretty sure I made sure it was still compatible for PHP 7.4 :)
