### ISSUE TITLE
Allow dynamic setting of baseUrl

### ISSUE THREAD

**Issue by vmosoti** [JustSteveKing/laravel-transporter#9]
If making a package that is consumed by different apps, it would be nice to set `baseUrl` dynamically through config files or similar

**Comment by JustSteveKing** [comment]
Thanks for the suggestion @vmosoti and I agree, however if I were to use this inside a package I might write some custom code wrapped around it to set the base Url.

I will have a look into what is possible, especially as we are extending the Laravel PendingRequest - if you fancy dropping a PR or writing down a "how I would use it" scenario I will add it to my todo list

**Comment by johndse** [comment]
Maybe we could just add a `baseUrl` method in the Request class that by default returns `$this->baseUrl` and in __construct we call:

```
 $this->request = $http->baseUrl($this->baseUrl());
```

If being able to call the decorated request baseUrl() method is important we could name the method something like `usingBaseUrl` or `getBaseUrl`.

**Comment by vmosoti** [comment]
@johndse my thoughts exactly

**Comment by JustSteveKing** [comment]
What I did recently @vmosoti and @johndse for an integration I am doing, and on stream was:

Create a base request for my integration for all others to extend upon, it looked like the following:

```php
<?php

declare(strict_types=1);

namespace App\Transporter\Requests\Acme;

use JustSteveKing\Transporter\Request;

abstract class AcmeRequest extends Request
{
    protected string $baseUrl = 'https://api.acme.com/';
}

```

Then the implementations were:

```php
<?php

declare(strict_types=1);

namespace App\Transporter\Requests\Acme;

class CustomerRequest extends AcmeRequest
{
    protected string $method = 'GET';

    protected string $path = 'customers';
}

```

What this did was allow me to create an abstract base request for each integration I needed to do - and at the same time allowing each request to override the base URL should they need to. This feels a little more flexible to me, as setting a base url for all of them may feel a little restrictive.

Happy to hear thoughts on this and change my mind if others feel there is a better way! Also, if I do extend this to allow it I will try to make it optional in some way.

**Comment by listefano** [comment]
In my current project I used the same solution as @JustSteveKing. I think this way should be fine for the most scenarios.

**Comment by JustSteveKing** [comment]
I agree @listefano - however I am more than happy to add this as a feature if people request it!

**Comment by vmosoti** [comment]
@JustSteveKing ,
Here is my scenario, I have a custom CRM app I make for my different customers (doing similar business) that integrates with an open source calling system that sits on its own server. From my app, I need to use _**Transporter**_ to interface my CRM to the calling system. All these apps sit in the individual customer data centers (few may prefer cloud).
Where my need arises is situations where one customer's network is 192.... another 172 ... yet another 10... e.t.c 

Assuming the calling server is 192.168.0.10 for one customer and 10.15.1.20 for another, this is where setting `baseUrl` via `ENV` is necessary.

Hope this visualises it for you.

Thanks much for your engagement.

**Comment by JustSteveKing** [comment]
@vmosoti this is a use case I never thought of if I am completely honest! I can see why this would be a requirement!

Let me see what I can do

**Comment by johndse** [comment]
I also think needing to change base URL to target a different environment i.e. testing vs production could be common.

**Comment by JustSteveKing** [comment]
How does this work as an example: [PR](https://github.com/JustSteveKing/laravel-transporter/pull/10)

Will merge and release if everyone is happy

@vmosoti @listefano @johndse

**Comment by listefano** [comment]
Just looked at the PR, looks good so far. Will try to test some scenarios later this day.

**Comment by JustSteveKing** [comment]
@listefano I added a basic test to ensure that the URI changes if it is set :)

**Comment by vmosoti** [comment]
The PR implementation is good, This will cover most scenarios under the use case

**Comment by JustSteveKing** [comment]
For those scenarios I can't think of easily, you can:

```php
YourRequest::build()->setBaseUrl('your-url)....
```

**Comment by JustSteveKing** [comment]
@vmosoti does the above changes solve your isues?

**Comment by JustSteveKing** [comment]
I have merged this branch now, if you want to discuss extending this functionality further please feel free to comment and I will reopen if required.

**Comment by JustSteveKing** [comment]
@vmosoti please see version 0.7.0

**Comment by vmosoti** [comment]
@JustSteveKing thanks. this sorts out my requirements
